### ISSUE TITLE
Desktop: Remove stroke on buttons

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#10]
![Screen Shot 2021-04-12 at 8 31 14 AM](https://user-images.githubusercontent.com/68758055/114394736-84fd5b80-9b69-11eb-9539-a0a59d5ff431.png)
![Screen Shot 2021-04-12 at 8 31 07 AM](https://user-images.githubusercontent.com/68758055/114394738-84fd5b80-9b69-11eb-8280-dac2c9083858.png)

**Comment by 1stevengrant** [comment]
resolved
