### ISSUE TITLE
Splash Page: Moving love forward image gone

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#100]
<img width="1680" alt="Screen Shot 2021-06-14 at 1 31 36 PM" src="https://user-images.githubusercontent.com/82427400/121934154-f053dd00-cd14-11eb-9ca4-8c25619589ef.png">

@1stevengrant

**Comment by 1stevengrant** [comment]
Hmmm, it shows for me on both desktop and mobile. Can you retest?

**Comment by joenicolette** [comment]
Hmm...I see it on mobile but still nothing on desktop for me. Chrome/Safari/Firefox. @1stevengrant

**Comment by joenicolette** [comment]
<img width="1680" alt="Screen Shot 2021-06-15 at 9 57 54 AM" src="https://user-images.githubusercontent.com/82427400/122066018-63665d80-cdc0-11eb-943d-7573a11e987e.png">

I also noticed it's showing an out of date version of the database for me. See the out of date image sizing for Shaunti.

**Comment by 1stevengrant** [comment]
Peculiar, I'll kick off a deployment, something might be caching although unusual it's working this end and mobile. 

I'll also sync the databases.

**Comment by 1stevengrant** [comment]
resolved by adding the dynamically generate asset url as a JavaScript variable into the layout. Really for my reference more than anything @joenicolette 😄
