### ISSUE TITLE
Splash: Seeing a wide range of expressions of this form field/button on various screen sizes

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#101]
<img width="500" alt="Screen Shot 2021-07-14 at 1 18 09 PM" src="https://user-images.githubusercontent.com/82427400/125664948-c00000d7-d78f-4df5-93e0-dd2bdce5937a.png">
<img width="1680" alt="Screen Shot 2021-07-14 at 1 19 06 PM" src="https://user-images.githubusercontent.com/82427400/125664934-2642e298-95a8-4fa0-90f8-1afc9b0a740c.png">
<img width="1075" alt="Screen Shot 2021-07-14 at 1 18 51 PM" src="https://user-images.githubusercontent.com/82427400/125664937-085c85f4-61c7-4c3e-8003-b4e96e0a8c78.png">
<img width="1017" alt="Screen Shot 2021-07-14 at 1 18 38 PM" src="https://user-images.githubusercontent.com/82427400/125664940-35cd98b3-1be9-47be-9253-bde1677b0579.png">
<img width="837" alt="Screen Shot 2021-07-14 at 1 18 29 PM" src="https://user-images.githubusercontent.com/82427400/125664942-c1310154-a838-4d7f-90ec-e41c87a735cf.png">
<img width="587" alt="Screen Shot 2021-07-14 at 1 18 15 PM" src="https://user-images.githubusercontent.com/82427400/125664945-a1c848bb-0abb-4121-be30-1e80dd6c148d.png">

@1stevengrant

**Comment by 1stevengrant** [comment]
yeah, it's relative to the container width and the container width changes as you scale the window
