### ISSUE TITLE
Videos tile has weird behavior below 780 pixels wide, Desktop

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#11]
![Screen Shot 2021-04-12 at 8 26 19 AM](https://user-images.githubusercontent.com/68758055/114395215-1a005480-9b6a-11eb-81ef-dd14ce6f90fb.png)

**Comment by 1stevengrant** [comment]
@gitethanwoo what's weird about the behaviour?

**Comment by gitethanwoo** [comment]
Looks like it was resolved with a different change!
