### ISSUE TITLE
MVP - PAGE (Menu) -"Become a Champion" needs to be "Register as Champion"

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#121]
<img width="251" alt="Screen Shot 2021-09-14 at 10 44 50 AM" src="https://user-images.githubusercontent.com/90408712/133279732-259f3718-a13e-4d0e-b99d-e71fda7c336a.png">

**Comment by 1stevengrant** [comment]
will resolve as part of https://github.com/loveology/loveology.org/pull/46
