### ISSUE TITLE
2. MVP - PAGE (Ask an Expert/Mobile) - Cards size and spacing between cards needs to match Figma 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#123]
Figma - <img width="398" alt="Screen Shot 2021-09-14 at 10 59 10 AM" src="https://user-images.githubusercontent.com/90408712/133282410-4b373068-e795-4dcf-8fcc-bb56040e1372.png">

Dev - 
<img width="497" alt="Screen Shot 2021-09-14 at 11 00 37 AM" src="https://user-images.githubusercontent.com/90408712/133282452-42b1520c-4634-4710-8b0c-bdf546dcfc70.png">

**Comment by 1stevengrant** [comment]
width of these cards is automatic based on the available screen size. However have tweaked the gap between
