### ISSUE TITLE
1. MVP - PAGE (Categories/Mobile) - Pills sizing 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#124]
Dev - <img width="418" alt="Screen Shot 2021-09-14 at 11 03 57 AM" src="https://user-images.githubusercontent.com/90408712/133284894-8139289f-9165-47aa-9182-b39c4242fb2b.png">

Figma - <img width="404" alt="Screen Shot 2021-09-14 at 11 04 06 AM" src="https://user-images.githubusercontent.com/90408712/133284931-b0bd7858-484b-4391-a819-975ec3ee4091.png">

**Comment by 1stevengrant** [comment]
will resolve with https://github.com/loveology/loveology.org/pull/46
