### ISSUE TITLE
3. MVP - PAGE (Categories/Mobile) - cards sizing needs to match Figma 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#126]
Dev - <img width="489" alt="Screen Shot 2021-09-14 at 11 04 25 AM" src="https://user-images.githubusercontent.com/90408712/133285079-ae41ccdd-3bc1-4d4f-9de8-2c7b4f2b9420.png">

Figma - 
<img width="443" alt="Screen Shot 2021-09-14 at 11 04 29 AM" src="https://user-images.githubusercontent.com/90408712/133285109-e196eb3f-b782-489c-81b0-890629d3ff69.png">

**Comment by 1stevengrant** [comment]
width of these cards is automatic based on the available screen size
