### ISSUE TITLE
4. MVP - PAGE (Categories/Mobile) - Author pictures are skewed 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#127]
<img width="59" alt="Screen Shot 2021-09-14 at 11 04 39 AM" src="https://user-images.githubusercontent.com/90408712/133285224-60f539f5-2228-49af-a399-b14875fe1575.png">

**Comment by 1stevengrant** [comment]
has resolved with @gitethanwoo's awesome new profile photos
