### ISSUE TITLE
MVP - PAGE (Categories/Desktop) - cards sizing needs to match Figma 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#129]
Figma - <img width="381" alt="Screen Shot 2021-09-14 at 11 22 48 AM" src="https://user-images.githubusercontent.com/90408712/133286458-be3dfc54-5da4-4306-95e3-c7a85b02fc41.png">

Dev - <img width="1048" alt="Screen Shot 2021-09-14 at 11 22 54 AM" src="https://user-images.githubusercontent.com/90408712/133286496-26a4ff68-fc01-4271-af74-9faeefd33cfb.png">

**Comment by 1stevengrant** [comment]
will be resolved by https://github.com/loveology/loveology.org/pull/46
