### ISSUE TITLE
MVP - PAGE (Categories/Desktop) - Author pictures are skewed 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#130]
Figma - 
<img width="406" alt="Screen Shot 2021-09-14 at 11 25 59 AM" src="https://user-images.githubusercontent.com/90408712/133286835-dfd5832c-ff63-44f8-91d0-12c04c87698b.png">

Dev - 
<img width="210" alt="Screen Shot 2021-09-14 at 11 25 49 AM" src="https://user-images.githubusercontent.com/90408712/133286854-27257f22-3de5-4a6d-80b7-b3b7ee56ddec.png">

**Comment by 1stevengrant** [comment]
has resolved with @gitethanwoo's awesome new profile photos
