### ISSUE TITLE
MVP - PAGE (Webinars/Desktop) - cards design and sizing needs to match Figma 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#131]
Figma - <img width="537" alt="Screen Shot 2021-09-14 at 12 04 29 PM" src="https://user-images.githubusercontent.com/90408712/133293651-ca5d0321-0bb1-4101-b56b-f800fde1613e.png">

Dev - j<img width="587" alt="Screen Shot 2021-09-14 at 12 04 34 PM" src="https://user-images.githubusercontent.com/90408712/133293672-bbd91c85-7e25-4796-8a39-22e29fe1f3b0.png">

**Comment by 1stevengrant** [comment]
width of these cards is automatic based on the available screen size. However have tweaked the gap between. Also webinars don't have an author
