### ISSUE TITLE
MVP - PAGE (Assessments/Desktop+Mobile) - Title aligned left 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#132]
Page needs to be created :) 

Figma - 
<img width="646" alt="Screen Shot 2021-09-14 at 12 26 39 PM" src="https://user-images.githubusercontent.com/90408712/133298043-55f5c292-8551-4c40-b724-d94d9a693b78.png">

Dev - 
<img width="1421" alt="Screen Shot 2021-09-14 at 12 26 12 PM" src="https://user-images.githubusercontent.com/90408712/133298082-699ce04f-df3a-47d1-bf64-8c6fd48b8c8f.png">

**Comment by 1stevengrant** [comment]
will resolve once assessment content is added
