### ISSUE TITLE
MVP - PAGE (Donate/Mobile) - Giving button needs to turn black and match form at the bottom 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#134]
Figma - 
<img width="170" alt="Screen Shot 2021-09-14 at 12 39 11 PM" src="https://user-images.githubusercontent.com/90408712/133299317-5d9c1504-c1bf-44d8-ad43-4c04f48bfbed.png">

Dev - 
![IMG_5242](https://user-images.githubusercontent.com/90408712/133299333-c4a9340d-572c-4391-bbde-3410aae484ab.jpg)

**Comment by 1stevengrant** [comment]
resolved with current deploy
