### ISSUE TITLE
MVP - PAGE (Donate/Desktop) - forever free font size and supporting text font size

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#135]
Figma - 
<img width="213" alt="Screen Shot 2021-09-14 at 12 53 45 PM" src="https://user-images.githubusercontent.com/90408712/133302975-89b1460b-09a0-40ef-a6e1-4da376a89e5f.png">

Dev - 
<img width="476" alt="Screen Shot 2021-09-14 at 12 53 50 PM" src="https://user-images.githubusercontent.com/90408712/133302990-feed9c38-8fc3-4cde-8c3b-44741b5d78f9.png">

**Comment by 1stevengrant** [comment]
consistent with figma
