### ISSUE TITLE
MVP - PAGE (Donate/Desktop) - Partner with us size and font 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#136]
Figma - 
<img width="221" alt="Screen Shot 2021-09-14 at 12 54 00 PM" src="https://user-images.githubusercontent.com/90408712/133303170-7b5aad3c-ffe7-40ab-8108-2a816fccc287.png">

Dev - 
<img width="449" alt="Screen Shot 2021-09-14 at 12 54 10 PM" src="https://user-images.githubusercontent.com/90408712/133303186-4f3140c9-27c7-426f-85a8-bd7a434c8b2e.png">

**Comment by 1stevengrant** [comment]
will resolve with https://github.com/loveology/loveology.org/pull/46
