### ISSUE TITLE
MVP - PAGE (Donate/Desktop) - Button color 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#137]
Figma - <img width="110" alt="Screen Shot 2021-09-14 at 12 58 19 PM" src="https://user-images.githubusercontent.com/90408712/133303629-1b0f217b-83ff-41a0-94d4-dac668a6c121.png">

Dev - 
<img width="257" alt="Screen Shot 2021-09-14 at 12 58 12 PM" src="https://user-images.githubusercontent.com/90408712/133303651-703f9970-35aa-47ea-b43e-c246bb01e815.png">

**Comment by garethredfern** [comment]
PR https://github.com/loveology/loveology.org/pull/44 addresses this.
