### ISSUE TITLE
MVP - PAGE (AboutUs/Desktop) - Title is off with background photo 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#138]
Figma - 
<img width="537" alt="Screen Shot 2021-09-15 at 11 56 11 AM" src="https://user-images.githubusercontent.com/90408712/133483977-bb516f7a-5bda-4263-a4d0-0ced6e012b6c.png">

Dev - 
<img width="735" alt="Screen Shot 2021-09-15 at 11 55 32 AM" src="https://user-images.githubusercontent.com/90408712/133483967-52a1166c-49da-45e8-87fa-5a3be2654982.png">

**Comment by 1stevengrant** [comment]
resolved
