### ISSUE TITLE
MVP - PAGE (AboutUs/Desktop) - Button color, incorrect red 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#139]
Figma - 
<img width="119" alt="Screen Shot 2021-09-15 at 11 56 54 AM" src="https://user-images.githubusercontent.com/90408712/133484230-359f2e32-3e7b-4772-86ca-1e07fdc396ee.png">

Dev - 
<img width="179" alt="Screen Shot 2021-09-15 at 11 56 57 AM" src="https://user-images.githubusercontent.com/90408712/133484213-4bc29232-b258-4956-9e4e-aae48af86623.png">

**Comment by 1stevengrant** [comment]
this uses the same `torch red` value defined in the brand color palette that we've pulled from Figma `F71A3A`
