### ISSUE TITLE
MVP - PAGE (AboutUs/Desktop) - “Our greatest experts font needs to match Figma + need to add expert photos 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#140]
Dev - 
<img width="470" alt="Screen Shot 2021-09-15 at 11 57 50 AM" src="https://user-images.githubusercontent.com/90408712/133484802-d6e00861-fd9d-490c-a37c-d82efc6cd89b.png">

Figma - 
<img width="565" alt="Screen Shot 2021-09-15 at 11 57 44 AM" src="https://user-images.githubusercontent.com/90408712/133484836-c94348bd-27ce-43b0-834a-1fa9dd558744.png">

**Comment by garethredfern** [comment]
PR https://github.com/loveology/loveology.org/pull/44 will address this.
