### ISSUE TITLE
MVP - PAGE (Video Page/Desktop) - Video bar does not match figma 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#143]
Figma - 
<img width="732" alt="Screen Shot 2021-09-21 at 11 58 53 AM" src="https://user-images.githubusercontent.com/90408712/134205406-7222e2d1-5456-4337-ba9d-62903ae5bd9f.png">

Dev 
<img width="849" alt="Screen Shot 2021-09-21 at 11 57 18 AM" src="https://user-images.githubusercontent.com/90408712/134205254-5e6283f3-f58f-4e22-ae24-bee82f7deb33.png">
-

**Comment by 1stevengrant** [comment]
we're using the native video controls once the video starts playing (so full screen isn't relevant at that point) and the share icon used doesn't exist in our feather icon set.
