### ISSUE TITLE
3. MVP - PAGE (Video Page/Desktop) - Share experience different from Figma / links to share on social do not work 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#145]
Dev - <img width="274" alt="Screen Shot 2021-09-21 at 12 03 06 PM" src="https://user-images.githubusercontent.com/90408712/134206197-4c95adb3-1f3f-4214-8579-a3f9d33d79a4.png">

Figma 
<img width="384" alt="Screen Shot 2021-09-21 at 12 04 27 PM" src="https://user-images.githubusercontent.com/90408712/134206302-fc33d8b8-a564-45d3-835b-88d0a1686c42.png">
-

**Comment by 1stevengrant** [comment]
intentional from my perspective on desktop. From a UX perspective, I shouldn't need to click share to then expose the share options. 

Mobile is different as we're using the share tool within the OS.
