### ISSUE TITLE
MVP - PAGE (Author Profile/Desktop) - Main image corners are too rounded 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#146]
Figma - 
<img width="752" alt="Screen Shot 2021-09-21 at 9 08 45 PM" src="https://user-images.githubusercontent.com/90408712/134267889-1f9ee706-b6e9-4d06-ba73-30425f19e536.png">

Dev -
<img width="1043" alt="Screen Shot 2021-09-21 at 9 09 04 PM" src="https://user-images.githubusercontent.com/90408712/134267898-6997c788-0283-48bd-8699-620b22fb54b2.png">

**Comment by 1stevengrant** [comment]
@gitethanwoo I added these to try make the best of the images we had, going to be hard to be prescriptive without having them all consistent, unless you're working on all profile images for this particular context?

**Comment by gitethanwoo** [comment]
@1stevengrant yes - we will have profile pictures for every author. should I upload them in dev.loveology?

**Comment by 1stevengrant** [comment]
will resolve with https://github.com/loveology/loveology.org/pull/48 and @gitethanwoo's new profile photos
