### ISSUE TITLE
4. MVP - PAGE (Author Profile/Desktop) -sort. button does not work  

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#147]
Dev -
<img width="49" alt="Screen Shot 2021-09-23 at 3 22 18 PM" src="https://user-images.githubusercontent.com/90408712/134570569-76c2b1b8-d2b9-496a-be4e-265fa68186fa.png">

**Comment by 1stevengrant** [comment]
will fix with https://github.com/loveology/loveology.org/pull/48 - removing the icon because it's not part of the code to make the dropdown work
