### ISSUE TITLE
Cannot create a webinar

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#156]
![Screen Shot 2021-09-30 at 5 53 24 PM](https://user-images.githubusercontent.com/68758055/135535237-a36a0a2b-a36e-42a0-b4f3-909ed1a67db8.png)

**Comment by 1stevengrant** [comment]
@gitethanwoo saw the error logs and it seems it was trying to add a webinar that already existed?

**Comment by 1stevengrant** [comment]
marking as resolved
