### ISSUE TITLE
Dev - Video Landing Page - Expert images auto. left justifying

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#157]
<img width="130" alt="Screen Shot 2021-10-03 at 11 09 20 PM" src="https://user-images.githubusercontent.com/82427400/135787420-16c762bc-2fae-4fef-a2ff-20f53195407d.png">

@1stevengrant

**Comment by 1stevengrant** [comment]
will be fixed with https://github.com/loveology/loveology.org/pull/51
