### ISSUE TITLE
Dev - Home Page - Change "Random" video carousel name to "New Releases"

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#159]
<img width="200" alt="Screen Shot 2021-10-03 at 11 14 16 PM" src="https://user-images.githubusercontent.com/82427400/135787809-4cd65c0a-d819-49db-8c40-632d2eb1313c.png">

@1stevengrant

**Comment by 1stevengrant** [comment]
will fix with https://github.com/loveology/loveology.org/pull/53
