### ISSUE TITLE
Dev - Mobile - Featured Video Player Page 

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#167]
@1stevengrant - Video rendering incorrectly 

![IMG_6050](https://user-images.githubusercontent.com/82427400/135789740-e060a64f-7dd3-4586-938d-6ecb8410efa3.PNG)
![IMG_6051](https://user-images.githubusercontent.com/82427400/135789743-16fdd127-f283-49bd-a1f3-b16c6b51d4ec.PNG)
![IMG_6052](https://user-images.githubusercontent.com/82427400/135789745-7871a534-2b06-44d3-9e24-423da9434615.PNG)

**Comment by 1stevengrant** [comment]
resolved in latest deploy
