### ISSUE TITLE
nav menus do not work while on About Us page. Clicking into them works, but you can't select any option.

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#200]
<img width="592" alt="Screen Shot 2021-10-09 at 4 08 17 PM" src="https://user-images.githubusercontent.com/68758055/136672550-6415a4d1-181c-4d70-ab01-7a926cc605be.png">

**Comment by garethredfern** [comment]
PR https://github.com/loveology/loveology.org/pull/65 fixes this
