### ISSUE TITLE
Home page banner - macbook take rounded corners taken out 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#233]
<img width="76" alt="Screen Shot 2021-10-14 at 12 41 02 PM" src="https://user-images.githubusercontent.com/90408712/137360660-addeb9fd-4ddd-4ade-ae61-82c35cb33047.png">

**Comment by 1stevengrant** [comment]
yah, that view above isn't specifically MacBook. We shouldn't really be referring to device names but rather screen size. 

MD in this instance is our `medium` breakpoint. For sizes between 768px and 1024px which is generally holding a tablet like you would hold a magazine. 

I see what you mean though, at that size, the corners shouldn't round. 

I'll reassign this to me :) 

Thanks.

**Comment by 1stevengrant** [comment]
will fix with https://github.com/loveology/loveology.org/pull/69
