### ISSUE TITLE
Videos went to 505 error 

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#243]
<img width="282" alt="Screen Shot 2021-10-19 at 2 24 51 PM" src="https://user-images.githubusercontent.com/90408712/137969197-4b82fd80-2cc5-4700-8e6b-d35ab474e19e.png">
<img width="264" alt="Screen Shot 2021-10-19 at 2 23 29 PM" src="https://user-images.githubusercontent.com/90408712/137969202-628c5e64-7a72-474f-8a25-3143958e8d84.png">

**Comment by 1stevengrant** [comment]
@kiaranicolette from where?

**Comment by 1stevengrant** [comment]
nvm @kiaranicolette I see it now....there's no related videos is the issue here. Re-assigning

**Comment by 1stevengrant** [comment]
resolved
