### ISSUE TITLE
Splash/Dev - "Get Connected" text updates

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#250]
Get updated on our latest videos, series, and speakers. --> We'll let you know when we post new videos.

<img width="383" alt="Screen Shot 2021-10-20 at 9 40 35 PM" src="https://user-images.githubusercontent.com/82427400/138202072-f695df0e-b992-48cb-b92c-8f4772698ff7.png">

@1stevengrant

**Comment by joenicolette** [comment]
@1stevengrant The subhead looks good, in "We'll let you know when we post new videos." but the header should read "We'd love to be connected." It was changed to the _former_ subhead

**Comment by joenicolette** [comment]
Splash looks great. Now, just need Dev component to match. :)
<img width="417" alt="Screen Shot 2021-10-21 at 8 50 41 PM" src="https://user-images.githubusercontent.com/82427400/138376109-f61dda18-de90-4866-9309-96a23c112bc1.png">

**Comment by 1stevengrant** [comment]
on next deploy
