### ISSUE TITLE
About Us Page: Scrollable version

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#255]
I have commented in Figma the location of the resizable screens. Please let me know any assets you may need or clarification!
![Screen Shot 2021-10-21 at 10 24 39 AM](https://user-images.githubusercontent.com/68758055/138297896-09274085-2aad-49ce-a29a-7e575e6a184d.png)

**Comment by 1stevengrant** [comment]
coming in next deploy

**Comment by gitethanwoo** [comment]
Looking so good! You nailed it!

Just one thing:
can we use the vertical author images?
![Screen Shot 2021-11-09 at 9 27 33 AM](https://user-images.githubusercontent.com/68758055/140942154-2903c6e4-b182-4eda-b393-8b5d6dfbfe8e.png)

**Comment by 1stevengrant** [comment]
Do we got those @gitethanwoo?

**Comment by gitethanwoo** [comment]
https://www.dropbox.com/sh/vriimil9gzjmig3/AAAuY4i5c32HW52nkECQxKHga?dl=0

**Comment by 1stevengrant** [comment]
coming in next deployment, just needs an image for Meg Meeker to be uploaded into Nova

**Comment by gitethanwoo** [comment]
looks great!!!
