### ISSUE TITLE
Intro video - end screen

### ISSUE THREAD

**Issue by mattylane** [loveology/issues#26]
At the end of the intro video, should it return to the zero state?

<img width="1440" alt="Screen Shot 2021-04-13 at 3 28 19 PM" src="https://user-images.githubusercontent.com/82327724/114629202-038ef180-9c6d-11eb-8f11-00359ba85fe2.png">

**Comment by 1stevengrant** [comment]
need to update the vimeo account to control - wonder if we should have the mailing list sign up at the end 🤔
