### ISSUE TITLE
Home page: category labels are too far from videos. Expected: 20 pixel padding. Current: 42 pixels.

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#267]
![Screen Shot 2021-10-25 at 11 57 37 AM](https://user-images.githubusercontent.com/68758055/138729910-cde5723d-500e-4e40-83bd-823f80bcbc8b.png)

Solution: Change 'padding-top' to 1rem for the carousel.

**Comment by gitethanwoo** [comment]
I believe the recent update to the mobile padding has recreated this issue

**Comment by gitethanwoo** [comment]
![Screen Shot 2021-11-03 at 11 00 22 AM](https://user-images.githubusercontent.com/68758055/140085515-f01d4970-307b-4441-a98f-7a1c0fbafc2a.png)

**Comment by 1stevengrant** [comment]
ah, this came back as a result of fixing the shadow on the card. Should be good on next deployment.

**Comment by gitethanwoo** [comment]
perfect
