### ISSUE TITLE
MOBILE: Category labels over carousels need padding to increase from .25rem to 1rem

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#279]
![IMG_1BF1748F5152-1](https://user-images.githubusercontent.com/68758055/138949886-2824d81a-87e8-4cb1-9537-7c8d08b55edd.jpeg)

**Comment by gitethanwoo** [comment]
Current:
![IMG_FE771D48EE64-1](https://user-images.githubusercontent.com/68758055/139703454-f203f4bb-40df-4810-905a-bd642728493a.jpeg)

Expected:
![Screen Shot 2021-11-01 at 12 09 10 PM](https://user-images.githubusercontent.com/68758055/139703486-9b466bef-aaff-4d37-9125-ad5454993ec9.png)

**Comment by garethredfern** [comment]
The next dev release fixes this. (https://github.com/loveology/loveology.org/pull/110)

**Comment by gitethanwoo** [comment]
beautiful

**Comment by 1stevengrant** [comment]
on next deploy

**Comment by gitethanwoo** [comment]
nice
