### ISSUE TITLE
MOBILE: Collapsed search icon does not match new search icon

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#280]
![Screen Shot 2021-10-26 at 3 45 21 PM](https://user-images.githubusercontent.com/68758055/138950108-ac7e6cfe-bd3d-405a-bf87-8f0ce0686108.png)

SVG link for reference:
https://drive.google.com/file/d/1xKWma6M6G3EVBKidXU6pHnEuzsT7sTGu/view?usp=sharing

**Comment by gitethanwoo** [comment]
can we change the fill to cod grey (#1A1A1A)  for just the collapsed search glass? Needs just a bit more contrast to be noticeable I think.

**Comment by 1stevengrant** [comment]
next deploy

**Comment by gitethanwoo** [comment]
![Screen Shot 2021-11-03 at 11 01 31 AM](https://user-images.githubusercontent.com/68758055/140085760-9257a8b9-e3d9-4b54-8ed0-29e81227d928.png)
![Screen Shot 2021-11-03 at 11 01 45 AM](https://user-images.githubusercontent.com/68758055/140085846-8dd788e7-9155-444a-911b-4a3431b48b2c.png)

Can we reverse these? so the collapsed search glass is dark and the expanded search is lighter

**Comment by 1stevengrant** [comment]
next deploy
