### ISSUE TITLE
MOBILE: card shadows are being cut off on bottom and right side. 

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#283]
![IMG_3335](https://user-images.githubusercontent.com/68758055/138954129-db97ed41-2185-4195-a952-075a7ac4ca4d.jpg)

**Comment by gitethanwoo** [comment]
Yes.

**Comment by 1stevengrant** [comment]
fixed for next deploy

**Comment by gitethanwoo** [comment]
beautiful
