### ISSUE TITLE
Desktop: remove pre-highlight from "One-time" and "25$" buttons

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#29]
Can we make the buttons white? hover turns beige and click turns red. Here's the Figma screenshot for reference.

![Screen Shot 2021-04-15 at 1 20 40 PM](https://user-images.githubusercontent.com/68758055/114911962-745d1780-9ded-11eb-9101-843f4346ccd8.png)

![Screen Shot 2021-04-15 at 1 22 10 PM](https://user-images.githubusercontent.com/68758055/114912080-96569a00-9ded-11eb-9aee-606abe5d2ba2.png)

**Comment by 1stevengrant** [comment]
Can do.

**Comment by 1stevengrant** [comment]
resolved
