### ISSUE TITLE
FAQ page: need to add the xl and 2xl images (1x jpgs included)

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#292]
XL image:
![xl image](https://user-images.githubusercontent.com/68758055/139090732-1043e91a-4fa8-438a-8487-40d6d0d830cc.jpg)

2XL Image:
![2xl image](https://user-images.githubusercontent.com/68758055/139090839-26c6feb5-7e72-4a21-8ca6-d7be88f31f5c.jpg)

**Comment by gitethanwoo** [comment]
The scaling issue is still occurring - at ultra wide, donate is great, but FAQ image keeps scaling up

![Screen Shot 2021-11-01 at 12 05 34 PM](https://user-images.githubusercontent.com/68758055/139702888-ed20f18c-922a-45d7-a5f7-af1410a7f83b.png)

![Screen Shot 2021-11-01 at 12 05 42 PM](https://user-images.githubusercontent.com/68758055/139702907-27a08edd-5946-46ab-aa65-3e5683febbc2.png)

**Comment by garethredfern** [comment]
The next dev release fixes this. (https://github.com/loveology/loveology.org/pull/110)

**Comment by gitethanwoo** [comment]
looks good
