### ISSUE TITLE
Can we downscale these pngs to approximately half height and ensure consistent margin?

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#293]
I've uploaded 2x pngs (all of them are 176px in height). If we could downscale them (for quality) that would be amazing.

I initially opened this because the logos appeared to be low quality and had inconsistent spacing.

![Screen Shot 2021-10-27 at 11 14 11 AM](https://user-images.githubusercontent.com/68758055/139095729-c728f1a6-b132-4175-a640-af4003267105.png)

**Comment by gitethanwoo** [comment]
Icon sizes are perfect. The centering is perfect. Is it possible to take down some of the vertical whitespace around the logos? 2.5 rem of whitespace would work above and below the logos. or alternatively, make the cards like 4 rem shorter overall. 

![Screen Shot 2021-11-02 at 10 20 29 AM](https://user-images.githubusercontent.com/68758055/139865578-c29b272c-bd01-41e9-b21b-815053a6a345.png)

**Comment by 1stevengrant** [comment]
in next deploy
