### ISSUE TITLE
The dev splash image/video should emulate the splash page

### ISSUE THREAD

**Issue by kiaranicolette** [loveology/issues#294]
Figma - <img width="345" alt="Screen Shot 2021-10-27 at 12 44 25 PM" src="https://user-images.githubusercontent.com/90408712/139110238-1bdaf61d-a859-4490-a6a3-ddccb590eeba.png">

Dev 
<img width="414" alt="Screen Shot 2021-10-27 at 12 43 00 PM" src="https://user-images.githubusercontent.com/90408712/139110279-5b6757c1-a67f-45d7-9ae4-50f89a4d1198.png">
-

**Comment by 1stevengrant** [comment]
have updated the video description in Nova for this

**Comment by joenicolette** [comment]
Ahh, ok. I updated the title to read "We're here for couples" and it looks like this
<img width="294" alt="Screen Shot 2021-11-01 at 10 51 16 AM" src="https://user-images.githubusercontent.com/82427400/139691362-9a9e20e4-cb50-4282-a544-e08eaee2b219.png">

**Comment by joenicolette** [comment]
Can we format so that it matches the splash page, like this? Stacking text and larger font.
<img width="436" alt="Screen Shot 2021-11-01 at 10 51 29 AM" src="https://user-images.githubusercontent.com/82427400/139691429-367473fe-a996-4ffc-be02-ba2a11a4ceec.png">

**Comment by 1stevengrant** [comment]
coming in next deploy

**Comment by gitethanwoo** [comment]
On BAM, subtext does not scale with main text. 

![Screen Shot 2021-11-12 at 9 40 15 AM](https://user-images.githubusercontent.com/68758055/141484513-8fa57b93-9f26-4b19-b7bd-16d886851149.png)

**Comment by 1stevengrant** [comment]
ah, yeah, I forgot to add the option for that.
