### ISSUE TITLE
Add a "Category" or similar header above these categories

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#299]
@gitethanwoo - may need to comp this out

<img width="659" alt="Screen Shot 2021-10-29 at 12 39 50 PM" src="https://user-images.githubusercontent.com/82427400/139471857-fcc97e83-3949-43b0-9ae6-b99aaff7010f.png">

**Comment by 1stevengrant** [comment]
will introduce on next deploy, no need for @gitethanwoo to comp but might wanna change the implementation

**Comment by joenicolette** [comment]
Thanks, Steven!

<img width="576" alt="Screen Shot 2021-10-30 at 8 47 49 PM" src="https://user-images.githubusercontent.com/82427400/139562273-f20083eb-31e1-4133-a280-4101c88ac378.png">

@gitethanwoo - love your input here. How can we maximize this?

**Comment by gitethanwoo** [comment]
![Screen Shot 2021-11-01 at 1 25 31 PM](https://user-images.githubusercontent.com/68758055/139713556-e6915b7a-12f1-4b69-991f-93b57d165f94.png)

Thoughts?

**Comment by joenicolette** [comment]
Strong. +1 from me.

**Comment by gitethanwoo** [comment]
@1stevengrant Let's actually go with 

" Tags: "

both Joe and Kiara preferred this way

**Comment by 1stevengrant** [comment]
on next deplou

**Comment by gitethanwoo** [comment]
looking **clean**
