### ISSUE TITLE
Desktop: can we also remove the autofilled amount and up/down buttons?

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#30]
![Screen Shot 2021-04-15 at 1 20 40 PM](https://user-images.githubusercontent.com/68758055/114912447-006f3f00-9dee-11eb-9f52-efa4660014cd.png)

I think the autofilled amount in the custom amount box is somewhat redundant. The up/down arrows also don't mesh with the overall appearance here.

**Comment by 1stevengrant** [comment]
can remove the up and down (although styles are browser dependent) but the prefilled amount needs to be there as it's dynamically bound to the button values above to work in the back end.

**Comment by 1stevengrant** [comment]
managed to come up with a good way for this to function
