### ISSUE TITLE
Provide New Create Account Images

### ISSUE THREAD

**Issue by garethredfern** [loveology/issues#300]
@gitethanwoo please can you provide all the correct images sizes as you did for the donate and ask pages.

Here is the code we use with size formats:

```
<source srcset="{{ asset('img/image-xl.jpg') }}"
        media="(min-width: 1280px)">
<source srcset="{{ asset('img/image-lg.jpg') }}"
        media="(min-width: 1024px)">
<source srcset="{{ asset('img/image-sm.jpg') }}"
        media="(min-width: 640px)">
<img class="lg:rounded-lg"
      src="{{ asset('img/image.jpg') }}"
      alt="">
```

**Comment by gitethanwoo** [comment]
For 1280 and up, XL:


![Hero section](https://user-images.githubusercontent.com/68758055/139709268-f8eacdf6-524f-4166-a09b-00b9a1706d88.jpg)

for 1024-1280, LG:

![unsplash_ELnxUDFs6ec](https://user-images.githubusercontent.com/68758055/139709291-a5776008-cfef-4a34-acd2-7b3630b63296.jpg)

for 640-1023:

![Hero section640](https://user-images.githubusercontent.com/68758055/139709769-59df84ad-bf44-4122-970f-4d3a18383c75.jpg)

for Mobile:
![Hero section mobile](https://user-images.githubusercontent.com/68758055/139709954-543b0bd7-035e-41a4-ac4c-9c0d8288bf30.jpg)
