### ISSUE TITLE
“How can I boost my listening skills as someone who helps couples?” 403 error. + Need a "prettier" error message.

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#302]
![File](https://user-images.githubusercontent.com/82427400/139562045-360e1460-9428-45ca-a647-2ae4effee14a.jpg)

**Comment by joenicolette** [comment]
@gitethanwoo - tagging you in as we'll likely need some sort of designed error state here. Thought we already had one, but maybe I'm wrong on that.

**Comment by 1stevengrant** [comment]
you're right @joenicolette - we do have designed error state but something has gone off in the deployment. Will resolve as part of another issue, so I'll close this
