### ISSUE TITLE
Search: video cards should always match the home page. Also, they're different sizes here.

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#303]
![IMG_6595](https://user-images.githubusercontent.com/82427400/139562165-a93b3ed0-2149-4542-9ff9-4fc95a6ea90f.PNG)

@gitethanwoo - may need some input here as to your design intention

**Comment by 1stevengrant** [comment]
unfortunately, it doesn't work like that. the sizes are auto calculated on based on the height of the tallest.
