### ISSUE TITLE
Search: Video cards are revealing the hour "00:", where they're not on the homepage

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#304]
<img width="1517" alt="Screen Shot 2021-10-30 at 8 44 11 PM" src="https://user-images.githubusercontent.com/82427400/139562211-4be194f7-7a52-43ad-b925-0a8d9f3bf2ad.png">

**Comment by 1stevengrant** [comment]
coming next deployment...seemingly dev was looking at the wrong Algolia index
