### ISSUE TITLE
Desktop - Video player page - essentially unable to click the "FAQs" and "Logout" options on this menu

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#305]
If I click either option, it selects the video card which is under the dropdown menu

<img width="606" alt="Screen Shot 2021-10-30 at 8 57 25 PM" src="https://user-images.githubusercontent.com/82427400/139562549-236344b9-4e52-47e8-bd18-301d7c87488b.png">

**Comment by 1stevengrant** [comment]
coming in next deployment
