### ISSUE TITLE
Welcome Video appearing in search bug is back

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#307]
Could be another Algolia index thing?

<img width="270" alt="Screen Shot 2021-10-31 at 2 13 26 PM" src="https://user-images.githubusercontent.com/82427400/139596457-4d43d987-eb43-47e2-b990-b9074c0cb95f.png">

**Comment by 1stevengrant** [comment]
Whackamole 😁

**Comment by 1stevengrant** [comment]
gone now
