### ISSUE TITLE
Login - Cached credentials look jumbled

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#308]
<img width="429" alt="Screen Shot 2021-10-30 at 8 53 53 PM" src="https://user-images.githubusercontent.com/82427400/139596514-7f810ba1-d968-46eb-b82d-5e6bd04ad5ab.png">

**Comment by 1stevengrant** [comment]
Do you have autocomplete?

Sent with a Spark

**Comment by joenicolette** [comment]
No, unless it comes as a standard feature of Chrome. Hmm...doesn't happen in Safari. Must be a Chrome thing.

**Comment by 1stevengrant** [comment]
Yeah - the only fix for us here would be to permanently move the label to always be above the input which I don't think @gitethanwoo wants.

**Comment by gitethanwoo** [comment]
![Screen Shot 2021-11-01 at 2 28 48 PM](https://user-images.githubusercontent.com/68758055/139722136-f064ba4e-8bdd-43be-a778-483f5e0cd9a8.png)

![Screen Shot 2021-11-01 at 2 28 41 PM](https://user-images.githubusercontent.com/68758055/139722296-f7593c2e-4b96-4c3f-b303-987681c5b7c8.png)

Google sign in page performs the intended behavior.. possible to copy that? 

meaning, google placeholder is within the input, but if you have autofill, it automatically transitions the placeholder above the input.

**Comment by gitethanwoo** [comment]
I'll just close for now - can be revisited for later iterations
