### ISSUE TITLE
Search logic

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#309]
What is the logic of our search results? Some queries yield no results. Other times, I'm prompted with the message encouraging me to "ask an expert" a question. Other times, I punch in a query that I know will yield no results, only to receive the entire catalog of videos as a result.

<img width="846" alt="Screen Shot 2021-10-31 at 2 19 42 PM" src="https://user-images.githubusercontent.com/82427400/139596899-47e859d8-2109-4a32-a2f2-43976b23bbb3.png">
<img width="1564" alt="Screen Shot 2021-10-31 at 2 20 34 PM" src="https://user-images.githubusercontent.com/82427400/139596900-555d0490-b067-4b7b-a188-70d891e824dc.png">
<img width="1566" alt="Screen Shot 2021-10-31 at 2 18 32 PM" src="https://user-images.githubusercontent.com/82427400/139596901-2fc950cf-c66e-4150-991c-a0127e27063f.png">

**Comment by 1stevengrant** [comment]
I haven't done much beyond setting up title, tags, expert and category to be searchable in Algolia

https://www.algolia.com/doc/guides/getting-started/how-algolia-works/in-depth/implementation-process/

You could definitely tweak that logic in Algolia. It's all driven from the UI, so you could play around with it.

Sent with a Spark
