### ISSUE TITLE
Still receiving "undefined601c0e5c" when following "Share" links

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#310]
<img width="382" alt="Screen Shot 2021-11-02 at 9 13 29 AM" src="https://user-images.githubusercontent.com/82427400/139853667-0bcc7551-e854-4b9f-bbc6-fef71eb69d60.png">

I know we've been through this before. Just replaying here as an item to track.

**Comment by 1stevengrant** [comment]
@joenicolette yeah, once I get Chipper CI hooked up, this will resolve this and the donation stuff.

All related.

**Comment by joenicolette** [comment]
Done! Chipper CI all sorted. :)

**Comment by 1stevengrant** [comment]
Saaawwwweeet - I'll jump on that this evening

**Comment by joenicolette** [comment]
Love it! Once we capitalize the "F" in featuring, we should be good!

<img width="369" alt="Screen Shot 2021-11-02 at 5 41 49 PM" src="https://user-images.githubusercontent.com/82427400/139955833-77d1083b-eef4-470b-ac73-ff71bdc24288.png">

**Comment by 1stevengrant** [comment]
will resolve on next deploy

**Comment by gitethanwoo** [comment]
love this
