### ISSUE TITLE
Bottom of hamburger menu still out of line

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#311]
<img width="264" alt="Screen Shot 2021-11-02 at 9 44 58 AM" src="https://user-images.githubusercontent.com/82427400/139859159-7e934caf-b6f6-40f0-a950-b030260fee39.png">

**Comment by joenicolette** [comment]
On mobile*

**Comment by 1stevengrant** [comment]
will resolve on next deploy

**Comment by gitethanwoo** [comment]
![IMG_3389](https://user-images.githubusercontent.com/68758055/140088012-95b65b7e-5b81-4bbd-a8f7-24b1d0641973.jpg)

The previous error has been fixed! however it still looks like there's some uneven spacing between the first 4 options compared with the last 5 options. The top 4 have too much spacing.

**Comment by 1stevengrant** [comment]
found it - next deploy

**Comment by joenicolette** [comment]
The sage continues. Spacing looks great while you're logged out. When you're logged in, the "Log Out" spacing is the issue.

<img width="191" alt="Screen Shot 2021-11-03 at 8 59 44 PM" src="https://user-images.githubusercontent.com/82427400/140239851-be2ab73c-12d6-405f-a751-82bbccd64264.png">
<img width="173" alt="Screen Shot 2021-11-03 at 8 59 34 PM" src="https://user-images.githubusercontent.com/82427400/140239852-d3c9228c-108c-468d-b16f-04649dc178a2.png">

**Comment by garethredfern** [comment]
next release - added fix

**Comment by gitethanwoo** [comment]
beatiful
