### ISSUE TITLE
Android - Some expert names are stacking on video cards

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#312]
<img width="351" alt="Screen Shot 2021-11-02 at 11 34 14 AM" src="https://user-images.githubusercontent.com/82427400/139879349-9b604be4-4156-48ef-8059-78e74023df2f.png">

**Comment by 1stevengrant** [comment]
@joenicolette this comes down to the screen size of the device ultimately...not much we can do here. Variations like these are acceptable, as long as the layout isn't breaking. You can't target Android only, so whatever we do here also impacts iOS.
