### ISSUE TITLE
Mobile (Android/iOS) "Watch Now" button not centered

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#314]
Seems to be the tiniest bit left justified
![IMG_91A3E4874EE8-1](https://user-images.githubusercontent.com/82427400/139880276-d08d2079-cb9a-4619-957a-f8e7b7e36fb6.jpeg)

**Comment by 1stevengrant** [comment]
@joenicolette this comes down to the screen size of the device ultimately...not much we can do here. Variations like these are acceptable, as long as the layout isn't breaking. You can't target Android only, so whatever we do here also impacts iOS.
