### ISSUE TITLE
Mobile (iOS/Android) - "FAQ" link under Ask an Expert page just drops you on the FAQs page

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#317]
Is there any way to have this open up a specific question under the FAQ page, like "What issues are the experts addressing?" for example?

<img width="402" alt="Screen Shot 2021-11-02 at 11 24 55 AM" src="https://user-images.githubusercontent.com/82427400/139880962-1412d677-ec41-4b0f-818e-550fd390cc4e.png">

**Comment by 1stevengrant** [comment]
unfortunately not, expanding the faq requires user interaction
