### ISSUE TITLE
Android - Donation flow, likely to be solved with our Chipper account

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#319]
<img width="406" alt="Screen Shot 2021-11-02 at 11 26 29 AM" src="https://user-images.githubusercontent.com/82427400/139887071-d6d4b04e-daf7-4d10-8522-86d6aa0d5e05.png">

**Comment by 1stevengrant** [comment]
@joenicolette Chipper all good and doing its things 🎉

**Comment by joenicolette** [comment]
<img width="1156" alt="Screen Shot 2021-11-02 at 5 39 47 PM" src="https://user-images.githubusercontent.com/82427400/139955541-15bfe2e5-0df2-42c2-a347-13cf0c59644b.png">

Same thing :(

**Comment by 1stevengrant** [comment]
@joenicolette at what point in the flow are you seeing this?

I've just completed a donation here https://d.pr/v/6ZUh5G - albeit the `thanks` page is unstyled but that's an easy fix. Not sure why this wouldn't be working for you.

**Comment by gitethanwoo** [comment]
https://github.com/loveology/issues/issues/198#issuecomment-959473835

Closing this issue.
