### ISSUE TITLE
All Sizes: Logo needs more left padding. At least 35 pixels

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#32]
![Screen Shot 2021-04-15 at 1 35 09 PM](https://user-images.githubusercontent.com/68758055/114913632-6c9e7280-9def-11eb-9bb5-d30b2f8ef810.png)

**Comment by 1stevengrant** [comment]
how about https://github.com/loveology/issues/issues/2 @gitethanwoo ?

**Comment by 1stevengrant** [comment]
resolved
