### ISSUE TITLE
"Connect" page. Can we add a "Return home" button or similar once a user has submitted their info? 

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#320]
<img width="377" alt="Screen Shot 2021-11-02 at 11 28 57 AM" src="https://user-images.githubusercontent.com/82427400/139887668-01e1afb3-6e72-4c22-bf30-bc58a5937eb4.png">

**Comment by 1stevengrant** [comment]
we use this component on the home page as well so have a call to action to `home` doesn't really make sense. That's what the nav menu and header logo is for 🙂

**Comment by gitethanwoo** [comment]
I'm going to close this, as I anticipate most users will interact with this on the home page, rather than on the connect page. If they do interact on the 'connect' page, as Steven has said, they have the header.
