### ISSUE TITLE
"Assessments" Page - can we add an outbound link icon to the "Take Assessment" button?

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#321]
Similar to the buttons that we added to off-site webinars

<img width="401" alt="Screen Shot 2021-11-02 at 11 30 04 AM" src="https://user-images.githubusercontent.com/82427400/139888628-778e975a-1970-4356-8e9a-db3b1bd81c84.png">

**Comment by 1stevengrant** [comment]
in next deploy

**Comment by gitethanwoo** [comment]
Looks good! can we:

- Increase the size of the icon to 1.5rem x 1.5rem
- increase padding-right on the text from .25rem to 1rem
- Change the padding of the button to padding-left:2rem, padding-right:1.25rem


Hoping to get something like this:
![Screen Shot 2021-11-03 at 11 30 41 AM](https://user-images.githubusercontent.com/68758055/140091550-4c5fe504-7dd0-4c45-b137-bc6442d2098a.png)

**Comment by 1stevengrant** [comment]
next deploy

**Comment by gitethanwoo** [comment]
amazing
