### ISSUE TITLE
Expert description in Expert cards

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#322]
Hey Steven - we were hoping we could get a short description section for the experts, so that users can quickly get an idea of who is who. 

was thinking brown LL, .75 REM. 

Thanks!

![Screen Shot 2021-11-02 at 3 18 06 PM](https://user-images.githubusercontent.com/68758055/139930492-9f72a3cf-a851-45ff-b019-82e177c4f76d.png)

**Comment by 1stevengrant** [comment]
yes! I had the same thought a while ago. I'll introduce a new `summary` field in Nova and then we can display that. I think we want a max length on this though. Give me a character count.

**Comment by 1stevengrant** [comment]
in next deploy. @gitethanwoo I thought that .75 was a little small in the context, so I bumped to .875

**Comment by gitethanwoo** [comment]
perhaps 60 max characters? It's hard to say exactly but that **should** only be 3 lines on the smallest author card.

**Comment by joenicolette** [comment]
Need these descriptions on the expert cards for the **Search** flow and the "**Browse All**" (experts) flow

<img width="1214" alt="Screen Shot 2021-11-03 at 2 14 19 PM" src="https://user-images.githubusercontent.com/82427400/140168951-1336847c-1c17-4f7c-8e42-d1e7335810ee.png">

<img width="1541" alt="Screen Shot 2021-11-03 at 2 14 33 PM" src="https://user-images.githubusercontent.com/82427400/140168937-59ad959a-acf2-4b4e-8655-6a834d565194.png">

**Comment by 1stevengrant** [comment]
in next deploy
