### ISSUE TITLE
SPLASH - donation confirmation image 

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#323]
![795038E1-C720-41AD-B87E-86D52661187F](https://user-images.githubusercontent.com/82427400/140006504-01dccb56-8e3e-4385-bb9e-46359a5a3d70.png)

Seems too zoomed in

**Comment by 1stevengrant** [comment]
will resolve on next deploy

**Comment by gitethanwoo** [comment]
looks great

**Comment by gitethanwoo** [comment]
Desktop is perfect, but **mobile** looks like there's still not enough margin on the sides
![IMG_3391](https://user-images.githubusercontent.com/68758055/140101697-7caaf9e9-828c-4183-b458-94e9cce56fd2.PNG)

**Comment by 1stevengrant** [comment]
I think @gitethanwoo thats a link on production and not dev? Based on your URL in the screenshot?

**Comment by gitethanwoo** [comment]
Yes - this is the splash page donate flow. @1stevengrant

**Comment by 1stevengrant** [comment]
Ah yes! Of course...read the title Steven🙈
