### ISSUE TITLE
Desktop: Share screen on video page covers nav menu drop down

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#324]
See Attached

![Screen Shot 2021-11-03 at 2 16 55 PM](https://user-images.githubusercontent.com/68758055/140169234-4ee3559f-d09c-450f-92d4-94c1e540075e.png)

**Comment by 1stevengrant** [comment]
coming on next deploy

**Comment by gitethanwoo** [comment]
still occurring
![Screen Shot 2021-11-04 at 11 44 44 AM](https://user-images.githubusercontent.com/68758055/140366799-afd3804c-fe03-464c-878a-ecdde6cd6c6b.png)

**Comment by 1stevengrant** [comment]
coming in next deploy
