### ISSUE TITLE
Search - Video cards aren't displaying as one standard size

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#329]
<img width="1158" alt="Screen Shot 2021-11-08 at 8 48 31 AM" src="https://user-images.githubusercontent.com/82427400/140753309-f6cfd05a-b1bf-4f62-aba0-888816ff3207.png">

**Comment by 1stevengrant** [comment]
next deploy

**Comment by gitethanwoo** [comment]
from what I can tell, solved
