### ISSUE TITLE
Resource cards need different appearance from regular video cards (I will shorten titles as well)

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#331]
current:
![Screen Shot 2021-11-08 at 1 27 48 PM](https://user-images.githubusercontent.com/68758055/140797471-badb018e-898e-4f0d-865e-355107578271.png)

Expected:
![Screen Shot 2021-11-08 at 1 28 37 PM](https://user-images.githubusercontent.com/68758055/140797575-76b73c2b-e9a9-4892-9084-14921fa0bd7b.png)

**Note: the image should be approximately 4:5 ratio.**

**Comment by 1stevengrant** [comment]
@gitethanwoo have all the images uploaded been sized matching that format? I'm going to need to create a new card component.

Right now, everything runs from a single card component with a couple of conditionals to slightly modify the appearance but seems like this is going to be distinct enough to merit a whole new component.

**Comment by 1stevengrant** [comment]
next deploy

**Comment by gitethanwoo** [comment]
Looks great!
