### ISSUE TITLE
Create account images are not the correct images yet

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#332]
Current
![Screen Shot 2021-11-08 at 12 39 46 PM](https://user-images.githubusercontent.com/68758055/140798739-9836e09a-3ba0-4aa9-8861-440450453755.png)

Expected:
![Screen Shot 2021-11-08 at 1 38 40 PM](https://user-images.githubusercontent.com/68758055/140798815-ffbfa22d-41c4-4776-88b7-b65fef1478e7.png)

**Comment by garethredfern** [comment]
Can you try clearing your browser cache please @gitethanwoo i have just checked on my phone and they are the correct ones.

**Comment by gitethanwoo** [comment]
@garethredfern Yes - I cleared everything and tried on chrome, tried on private browse on desktop safari, tried on private browse mobile safari as well. Still the wrong images

**Comment by gitethanwoo** [comment]
I'm entering a fake email and password to 'create a new account' each time I'm testing. the initial page is the correct image

**Comment by garethredfern** [comment]
fixed in the next release
