### ISSUE TITLE
Create Account Flow: Strange behavior of floating labels

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#334]
When you are typing into a field, the floating label looks fine. when you go to the next field, the previous floating label floats even higher, causing uncomfortable spacing issue, which is unexpected

![Screen Shot 2021-11-08 at 1 49 12 PM](https://user-images.githubusercontent.com/68758055/140800831-b59f74af-25b3-47aa-8406-9f0b9a0032ef.png)

![Screen Shot 2021-11-08 at 1 49 24 PM](https://user-images.githubusercontent.com/68758055/140800841-438ea907-b24e-4832-9fe9-379f266ac906.png)

**Comment by garethredfern** [comment]
fixed in next release
