### ISSUE TITLE
Create Account flow: please round corners on progress bars

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#335]
Current:
![Screen Shot 2021-11-08 at 2 03 41 PM](https://user-images.githubusercontent.com/68758055/140802038-eb1b14a2-7c54-41c6-bbc1-2add192441ff.png)

Expected
![Screen Shot 2021-11-08 at 2 04 05 PM](https://user-images.githubusercontent.com/68758055/140802114-56d49e9c-4462-4b8d-8b36-cccf2614e8e3.png)
:

**Comment by garethredfern** [comment]
updated in the next release
