### ISSUE TITLE
Create Account Flow: strange interactions, probably due to floating label behavior

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#336]
I believe this may be an extension of the other issue I posted, but just posting this to be thorough

![Screen Shot 2021-11-08 at 12 41 24 PM](https://user-images.githubusercontent.com/68758055/140802200-f7f631e2-fc9f-443f-a606-5e78ca323d1b.png)

**Comment by garethredfern** [comment]
fixed in next release
