### ISSUE TITLE
Cross on home page too large - scale to 0.5 to fall in line with search results page.

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#337]
![Screen Shot 2021-11-09 at 9 17 34 AM](https://user-images.githubusercontent.com/68758055/140940535-dbde4ef5-117a-480a-a19b-0c6ea24cb211.png)

**Comment by 1stevengrant** [comment]
coming in next deploy

**Comment by gitethanwoo** [comment]
closing, as the cross is no longer relevant
