### ISSUE TITLE
Splash - Replace "Explore" graphics

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#338]
<img width="2240" alt="Screen Shot 2021-11-09 at 9 03 29 AM" src="https://user-images.githubusercontent.com/82427400/140944677-f75d29a2-bd17-4277-a862-cd797b6e597c.png"

Here are the images to use with the correct spelling of Dave's last name *sigh*
![explore-phone](https://user-images.githubusercontent.com/82427400/140944814-111ad8ae-e978-4dcc-aff0-da7b8364f096.png)
![explore-tablet](https://user-images.githubusercontent.com/82427400/140944824-01f65cb1-22e2-403a-8001-90a2cd125b5f.png)
![explore-desktop](https://user-images.githubusercontent.com/82427400/140944830-2ab5f63e-c49a-4aa7-86d4-d8612ca296b1.png)
![explore-bam](https://user-images.githubusercontent.com/82427400/140944834-e7d8d6cc-a53e-4992-83a8-206f6db2baee.png)
>

**Comment by 1stevengrant** [comment]
coming in next deploy to production

**Comment by gitethanwoo** [comment]
Looks like something is off with the splash page right now.

![Screen Shot 2021-11-11 at 2 36 58 PM](https://user-images.githubusercontent.com/68758055/141358253-025b41ef-0a6a-4d1b-b354-4b46e2eb649e.png)

**Comment by gitethanwoo** [comment]
@1stevengrant is this expected behavior - with the tiling?

**Comment by 1stevengrant** [comment]
Nothing changed other than an image replacement, were the image sizes correct? I didn't actually check for the same sizes.

**Comment by 1stevengrant** [comment]
@gitethanwoo seems these new images were indeed different sizes from the ogs. Here's my diff tool report...

![difference of images](https://d.pr/i/wZEMHt+)

**Comment by gitethanwoo** [comment]
I did my best to match the sizes exactly. These differences must have arisen from different people exporting the same thing differently.

Explore-bam:
<img width="1721" alt="explore-bam" src="https://user-images.githubusercontent.com/68758055/141484193-a3d37598-0633-4cc1-a109-24ba03657e2e.png">

Explore-desktop:
<img width="930" alt="explore-desktop" src="https://user-images.githubusercontent.com/68758055/141484220-2c1c8671-865d-4054-a5fd-d8bd520920de.png">

explore-phone:
![explore-phone](https://user-images.githubusercontent.com/68758055/141484245-7ffa44d1-73f5-4ba7-8d9b-02f88d749544.png)

explore-tablet:

![explore-tablet](https://user-images.githubusercontent.com/68758055/141484273-93f0a272-fa62-40ae-9997-9bac32155b20.png)
