### ISSUE TITLE
Ask the Expert

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#34]
Unsure if this form is hooked up right now, but I'm getting "**_We need your email address to keep you informed_**" and "**_What would you like to ask us?_**" despite having both fields populated. 

<img width="370" alt="Screen Shot 2021-04-15 at 10 17 02 PM" src="https://user-images.githubusercontent.com/82427400/114962327-7c8e7480-9e38-11eb-9849-474b853d4d9b.png">

**Comment by 1stevengrant** [comment]
resolved
