### ISSUE TITLE
Can we switch sides on the form and image for these sections? 

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#341]
The goal is that each section on the homepage is alternating as you scroll down (form left, then form right, etc).

I **believe** this is the most efficient way to do it.

![Screen Shot 2021-11-10 at 9 27 44 AM](https://user-images.githubusercontent.com/68758055/141131295-8fe31468-91c4-406b-8e7f-907c89ef7ac2.png)
![Screen Shot 2021-11-10 at 9 30 50 AM](https://user-images.githubusercontent.com/68758055/141131821-7e8e7132-185a-4625-82a3-6bab796d56fe.png)

**Comment by garethredfern** [comment]
These components are shared components so if sides are changed for the home page they will be changed on the individual pages too. Unless you want me to add in a variable so I can set the order?

**Comment by 1stevengrant** [comment]
Yeah we want to avoid that level of complexity really.

Can see it giving problems down the line.

I say whatever happens on home, echoes everywhere else.

**Comment by gitethanwoo** [comment]
We can switch sides within the individual pages - not a problem at all.

**Comment by garethredfern** [comment]
Updated on next release.
