### ISSUE TITLE
Create Account Flow - need to update the last step form

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#342]
With the updates to the create account flow, we made a change to the last 2 steps in the flow.

We got rid of this screen:
![Screen Shot 2021-11-10 at 9 33 50 AM](https://user-images.githubusercontent.com/68758055/141133289-1fb338ce-6e1a-430b-8c56-0d5f20c3651f.png)

And edited this screen:
![Screen Shot 2021-11-10 at 9 33 54 AM](https://user-images.githubusercontent.com/68758055/141133294-8a38b33d-d52a-4979-9e70-a948873548b5.png)

So the confirmation screen should be:
![Screen Shot 2021-11-10 at 9 41 32 AM](https://user-images.githubusercontent.com/68758055/141133662-5e8ac621-273d-492c-a9f9-27ef988bf70d.png)

**Comment by garethredfern** [comment]
Can you upload an image I can use for this please:

<img width="115" alt="Screenshot 2021-11-11 at 14 08 16" src="https://user-images.githubusercontent.com/246458/141312083-e84839c1-6392-42d6-97e7-1e46bb54f226.png">

**Comment by joenicolette** [comment]
Think we'll have to scrub this whole flow

**Comment by joenicolette** [comment]
<img width="351" alt="Screen Shot 2021-11-11 at 9 48 47 AM" src="https://user-images.githubusercontent.com/82427400/141318426-095346df-e420-4d4b-92f5-540c4c83948a.png">

This needs to be a dropdown with selectable options. The options are here:
<img width="705" alt="Screen Shot 2021-11-11 at 9 52 38 AM" src="https://user-images.githubusercontent.com/82427400/141318721-5f790e03-ed14-4d76-ab85-beaff3d23c88.png">

**Comment by joenicolette** [comment]
"Approximately how many couples do you counsel/coach per year?" Should have another selectable dropdown with these options:

Less than 5
5-10
11-20
21+

Waiting on @gitethanwoo to confirm this number set

**Comment by joenicolette** [comment]
<img width="356" alt="Screen Shot 2021-11-11 at 9 48 52 AM" src="https://user-images.githubusercontent.com/82427400/141319572-9acf14d2-9a08-49b1-bab9-4fad71da2038.png">

This text should now read: "I’d like to see Faith-based content"

**Comment by joenicolette** [comment]
- Bring SYMBIS next to Prepare/Enrich on a third line
- Ph.D --> Doctoral Degree

<img width="393" alt="Screen Shot 2021-11-11 at 9 49 23 AM" src="https://user-images.githubusercontent.com/82427400/141320296-e0cfbe33-8a46-4c30-81b5-d8ad649d7f7b.png">

**Comment by garethredfern** [comment]
@joenicolette sorry can you explain what Ph.D --> Doctoral Degree means?

Also in terms of moving these onto different lines that is not really possible as they are flexible depending on what screen width you are at. This is how responsive design is meant to flow.

**Comment by gitethanwoo** [comment]
@garethredfern he means to change the 'PhD' button to a button that reads 'Doctoral Degree'

Also: here's a 2x png that you requested.

<img width="176" alt="Example Champion Card" src="https://user-images.githubusercontent.com/68758055/141488057-c1984409-4629-45b2-ae50-207ecbcf1223.png">

**Comment by garethredfern** [comment]
Ready to test in next release.

**Comment by joenicolette** [comment]
Looks good to me. Feel free to give this a once over and close @gitethanwoo
