### ISSUE TITLE
Search - Remove "Champion Specific" categorical tag for user who aren't logged in

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#343]
Clicking this bubble yields no results, as it should, but the next step would be to eliminate it altogether, if possible.

<img width="1210" alt="Screen Shot 2021-11-10 at 9 52 57 AM" src="https://user-images.githubusercontent.com/82427400/141135760-010eff2b-6d22-4f5f-a9d9-741dd3298f48.png">

**Comment by 1stevengrant** [comment]
coming on next deploy
