### ISSUE TITLE
Browse/Categories/Video page - Seeing "Moving Love Forward, Together" graphic under the videos when I scroll fast

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#344]
<img width="2239" alt="Screen Shot 2021-11-11 at 9 37 38 AM" src="https://user-images.githubusercontent.com/82427400/141316650-ed550e4f-d698-440c-84d5-2f0bbfb8daa1.png">

**Comment by 1stevengrant** [comment]
coming in next deploy
