### ISSUE TITLE
About Us - “Our Greatest Experts” --> “Our Experts”

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#347]
+ Meg Meeker's profile image isn't loading

<img width="716" alt="Screen Shot 2021-11-11 at 10 13 39 AM" src="https://user-images.githubusercontent.com/82427400/141322061-cdc62a30-7816-43e2-97d5-e31e20d1461d.png">

**Comment by 1stevengrant** [comment]
@joenicolette that's correct...I didn't have one for her. Needs to be uploaded in Nova when we have it.

text change coming in next deploy though.
