### ISSUE TITLE
Button Chevron Spacing/Sizing *nitpick*

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#35]
- Chevron placement seems a bit off our center line in these two buttons.
- Also, the "Watch Now" chevrons seem a bit small. *opinion*

<img width="235" alt="Screen Shot 2021-04-15 at 10 19 17 PM" src="https://user-images.githubusercontent.com/82427400/114962453-b495b780-9e38-11eb-8a8c-dcba358b08c3.png">
<img width="223" alt="Screen Shot 2021-04-15 at 10 19 02 PM" src="https://user-images.githubusercontent.com/82427400/114962457-b52e4e00-9e38-11eb-82d5-57de7981e3b9.png">
<img width="344" alt="Screen Shot 2021-04-15 at 10 21 27 PM" src="https://user-images.githubusercontent.com/82427400/114962579-eeff5480-9e38-11eb-8c19-1e4c6298a704.png">

**Comment by 1stevengrant** [comment]
yeah I'd like to have more consistent button sizes/styles generally - will bring this up tonight

**Comment by 1stevengrant** [comment]
resolved
