### ISSUE TITLE
Browse - Some categories aren't surfacing as pills

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#350]
Examples are: **Anger, Abuse, Money, Finances, Grief, Personality, Pre-Marriage**

We have videos associated with these^ tags, but those categories aren't showing as sortable pills
<img width="1192" alt="Screen Shot 2021-11-15 at 9 45 08 AM" src="https://user-images.githubusercontent.com/82427400/141801888-7384df3c-abe0-43a6-83ce-73370f61ceb5.png">

**Comment by 1stevengrant** [comment]
@garethredfern I actually discovered this looking at something else, just needed to tweak the Algolia `maxFacetHits` setting
