### ISSUE TITLE
Learn More - Video card size/spacing irregularities 

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#352]
<img width="598" alt="Screen Shot 2021-11-15 at 9 06 02 AM" src="https://user-images.githubusercontent.com/82427400/141997904-5a736dd8-5369-4aa7-98ee-0acee779a150.png">
<img width="599" alt="Screen Shot 2021-11-15 at 9 05 09 AM" src="https://user-images.githubusercontent.com/82427400/141997911-9b82efd7-e0d0-41f3-888f-eed73aed3472.png">
<img width="598" alt="Screen Shot 2021-11-15 at 9 04 45 AM" src="https://user-images.githubusercontent.com/82427400/141997913-ec788801-b8fc-4798-b2ae-187574e60b3d.png">

**Comment by joenicolette** [comment]
Are these containers conforming to the size of the image that's loaded into it?

**Comment by 1stevengrant** [comment]
These images are going to need to be consistent in their aspect ie portrait in order that the size is set.

**Comment by 1stevengrant** [comment]
can we keep these to 200px wide by 248px high when uploaded to Nova @joenicolette ? It's the only way these will work.

**Comment by joenicolette** [comment]
@gitethanwoo - Please see Steven's note above and close
