### ISSUE TITLE
Capitalization in "Donate ____ Now"

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#36]
I believe this "N" should be lowercase to be consistent with our other buttons.

<img width="221" alt="Screen Shot 2021-04-15 at 10 22 20 PM" src="https://user-images.githubusercontent.com/82427400/114962695-2bcb4b80-9e39-11eb-8a31-ff659044d9d6.png">

**Comment by 1stevengrant** [comment]
resolved
