### ISSUE TITLE
"Email Addresses Don't Match" Prompt

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#38]
Whenever I type in two different addresses, I'm not prompted with something along the lines of "Whoops! Looks like those fields don't match!" or something along those lines, and when I click the give button, it doesn't do anything either.
<img width="540" alt="Screen Shot 2021-04-15 at 10 47 19 PM" src="https://user-images.githubusercontent.com/82427400/114964368-9762e800-9e3c-11eb-853d-11f39cf7f1cd.png">

**Comment by 1stevengrant** [comment]
resolved
