### ISSUE TITLE
Stripe: "Subscribe to Donation"

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#40]
Assuming this will be fixed when we hook up our Stripe account/API key
<img width="442" alt="Screen Shot 2021-04-15 at 10 50 11 PM" src="https://user-images.githubusercontent.com/82427400/114964826-7c44a800-9e3d-11eb-8ab1-dc6483a5f41b.png">

**Comment by 1stevengrant** [comment]
it will yeah, this was a sample thing in my own Stripe account. I've changed it now for demo purposes.
