### ISSUE TITLE
Successful Donation Copy

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#41]
Should this read "xxxxx, thank you for your **_monthly_** donation of $xxxxx" since I opted to donate monthly?
<img width="941" alt="Screen Shot 2021-04-15 at 10 54 30 PM" src="https://user-images.githubusercontent.com/82427400/114964887-9a120d00-9e3d-11eb-838c-1ea0bfb968c0.png">

**Comment by 1stevengrant** [comment]
@joenicolette it could, for sure - I'm easy on whatever. I've added this for now but I guess it might changed depending on what comes from Ranj.
