### ISSUE TITLE
"Back to Loveology" Button URL

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#42]
Upon a successful donation, this button sends me to "https://staging.loveology.org/" (the "coming soon" page) instead of "/splash"
Maybe this will be fixed on go-live. 
<img width="1044" alt="Screen Shot 2021-04-15 at 10 58 51 PM" src="https://user-images.githubusercontent.com/82427400/114965290-4fdd5b80-9e3e-11eb-965d-aa5a2cd1bc7e.png">

**Comment by 1stevengrant** [comment]
yeah, that's correct @joenicolette . When we go live, the splash will live at that URL
