### ISSUE TITLE
Returning to Loveology Following a Successful Donation

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#43]
The only way I could find to head back to Loveology from Stripe's donation experience was clicking on the logo in the top left, which could make sense since it's Stripe's platform, but this logo is also pointing to "https://staging.loveology.org/" instead of "/splash"

<img width="1072" alt="Screen Shot 2021-04-15 at 11 01 14 PM" src="https://user-images.githubusercontent.com/82427400/114965426-8d41e900-9e3e-11eb-8b6a-b78e28b310b6.png">

**Comment by 1stevengrant** [comment]
yeah, that's correct @joenicolette . When we go live, the splash will live at that URL
