### ISSUE TITLE
Header - Logo size and placement

### ISSUE THREAD

**Issue by mattylane** [loveology/issues#44]
The logo is still too big (check figma for sizing). Also, the padding from left to browser window should stay consistent.

**Comment by 1stevengrant** [comment]
@mattylane cool - I'd reduced by 20% previously but I'll pin this to the exact height in Figma. 

In terms of padding it's shown as 

![](https://d.pr/i/mHWlVZ+)

**Comment by 1stevengrant** [comment]
resolved
