### ISSUE TITLE
Mobile: "One time" is still stacking under the "Partner with us." section

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#47]
![IMG_2896](https://user-images.githubusercontent.com/82427400/115279811-2a3da400-a115-11eb-8ac1-3229f924f804.jpeg)

**Comment by 1stevengrant** [comment]
@joenicolette can you give some context around where you're seeing that?

**Comment by joenicolette** [comment]
On mobile :)

**Comment by 1stevengrant** [comment]
yeah, which mobile though?  I'm on iPhone 8+

**Comment by joenicolette** [comment]
Ahh, sorry. iPhone 12 Pro.

**Comment by 1stevengrant** [comment]
resolved
