### ISSUE TITLE
Mobile: "Forever Free" + "Partner with us." section need to be combined

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#48]
![IMG_8F83AE527617-1](https://user-images.githubusercontent.com/82427400/115282849-abe30100-a118-11eb-91b3-645f04924483.jpeg)

**Comment by joenicolette** [comment]
These can be independant (side by side) on iPad, Macbook, and BAM screen sizes.

**Comment by joenicolette** [comment]
"“Free Forever” should be a subset of the element below" - a note out of our work stream review meeting.

**Comment by 1stevengrant** [comment]
resolved
