### ISSUE TITLE
Mobile: <p> </p> tags appearing in FAQ text

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#52]
![IMG_2907](https://user-images.githubusercontent.com/82427400/115442555-24f95b80-a1e0-11eb-9836-e6bdcacdfc54.PNG)
![IMG_2906](https://user-images.githubusercontent.com/82427400/115442558-2591f200-a1e0-11eb-9f2f-19d9245d2f49.PNG)
![IMG_2905](https://user-images.githubusercontent.com/82427400/115442560-2591f200-a1e0-11eb-918f-1d8cae965ca3.PNG)
![IMG_2904](https://user-images.githubusercontent.com/82427400/115442564-262a8880-a1e0-11eb-8118-57452998f634.PNG)
![IMG_2903](https://user-images.githubusercontent.com/82427400/115442566-26c31f00-a1e0-11eb-93a7-1bcc23e27fe4.PNG)

**Comment by 1stevengrant** [comment]
@joenicolette deploying resolution for this now
