### ISSUE TITLE
Stripe Donation Experience "Test Mode"?

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#55]
Assuming this is a switch that you'll flip upon go-live. Just wanted to mark it.

<img width="316" alt="Screen Shot 2021-04-21 at 8 52 51 PM" src="https://user-images.githubusercontent.com/82427400/115639825-8eae5e00-a2e3-11eb-9fdc-f53ac76dfa51.png">

**Comment by 1stevengrant** [comment]
yeah, there's nothing to do here on this
