### ISSUE TITLE
MOBILE: Video player issues

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#57]
- Upon clicking play button, the video doesn't play. 
- In order to play the video, you need to click anywhere on the video, then click the play button
- This current iteration requires 3 clicks to access the video instead of one (simply tapping the big red "play" button)
- VIDEO found below

https://user-images.githubusercontent.com/82427400/115640717-9838c580-a2e5-11eb-925b-ac2c3712242f.mov

**Comment by 1stevengrant** [comment]
I agree with this but there is an iOS browser limitation. 

That first element we see isn't the video, it's an image, it's not until the modal pops that the video is revealed and it's the play button there that is able to initialise play.

Desktop is more forgiving. These are things that I need more than a handful of days to build.

**Comment by 1stevengrant** [comment]
resolved
