### ISSUE TITLE
Terms + Privacy Policy are still bacon ipsum. Mentioned to Ranjy.

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#59]
![IMG_2968](https://user-images.githubusercontent.com/82427400/115642500-121e7e00-a2e9-11eb-91f3-5bfe0bed5d73.PNG)
![IMG_2967](https://user-images.githubusercontent.com/82427400/115642506-13e84180-a2e9-11eb-91eb-462a55aeddbc.PNG)

**Comment by 1stevengrant** [comment]
resolved
