### ISSUE TITLE
MOBILE: Donation form sizing looks off.

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#61]
iPhone 12 Pro for reference.

- One time should be on one line
- The centering seems a bit off. Monthly is almost touching the outside of its box. I'm sure you'll see the issues here!

![IMG_2970](https://user-images.githubusercontent.com/82427400/115723178-b33f2000-a34d-11eb-9f02-c88e60162673.PNG)

**Comment by 1stevengrant** [comment]
yeah, smaller screen size than I have on my pro, have resolved pending release
