### ISSUE TITLE
MOBILE: Video Player

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#62]
iPhone 12 Pro, for reference.
Jonathan Hoover's credentials are covered by the iOS toolbar. Should we ask Doug to move this lower thirds graphic/animation up a bit, similar to how we moved the "playbar" up for mobile devices?

![IMG_2975](https://user-images.githubusercontent.com/82427400/115732888-63188b80-a356-11eb-9c03-3687bfd07c24.PNG)

**Comment by 1stevengrant** [comment]
issues could be addressed by #63
