### ISSUE TITLE
MOBILE: Video Player

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#64]
When a video ends, I'm presented with a freeze frame of the video outro with no buttons or direction on how to watch the next video or head back to the splash page. Is this a design issue? 

![IMG_2978 2](https://user-images.githubusercontent.com/82427400/115741706-f99c7b00-a35d-11eb-9b15-d41401fc4968.jpg)

**Comment by joenicolette** [comment]
@1stevengrant

**Comment by 1stevengrant** [comment]
yeah, we'll need some design work on defining how the next video should be highlighted
