### ISSUE TITLE
ANDROID: Splash video play button remains on screen while video plays

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#66]
Hero video plays upon clicking the play button, but the play button doesn't go away, also there are no play/pause/etc. controls.
<img width="340" alt="Screen Shot 2021-04-26 at 9 41 37 AM" src="https://user-images.githubusercontent.com/82427400/116092262-a71bd100-a673-11eb-84a5-767278bb1108.png">

**Comment by 1stevengrant** [comment]
so android works entirely differently - need to chew on it

**Comment by 1stevengrant** [comment]
resolved and tested on a crappy little Android device I had kicking around - better devices should be even smoother
