### ISSUE TITLE
ANDROID: Video thumbnail rendering is off

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#67]
<img width="341" alt="Screen Shot 2021-04-26 at 9 40 23 AM" src="https://user-images.githubusercontent.com/82427400/116092501-daf6f680-a673-11eb-934a-ea45bcf2ef83.png">

**Comment by joenicolette** [comment]
Samsung Galaxy S20, for reference @1stevengrant

**Comment by 1stevengrant** [comment]
new video cards have resolved
