### ISSUE TITLE
iOS - Video Player Issues

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#69]
Ok, here we go. iPhone 12 Pro.

When viewing the hero video then swiping out of the mobile browser to another app, the video will play as picture in picture as intended. See this image.
![IMG_3082](https://user-images.githubusercontent.com/82427400/116135893-a862f300-a69f-11eb-9835-65a4f79ff31d.jpg)

If you were to close out of this video, then play one of the videos from the "Videos" component, then go BACK to the hero video, you lose player controls and picture in picture VIDEO doesn't work, although I still have audio.

![IMG_3080](https://user-images.githubusercontent.com/82427400/116136059-d6483780-a69f-11eb-8078-421984c97751.jpg)
Please see these images.
![IMG_3081](https://user-images.githubusercontent.com/82427400/116136035-d1838380-a69f-11eb-828c-0d7169339a1e.jpg)

@1stevengrant

**Comment by 1stevengrant** [comment]
resolved
