### ISSUE TITLE
BAM - Hero video container size

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#70]
I don't see the corners rounded in any other resolution, and the black line on top. Is this upon video export, or a dev thing?

<img width="228" alt="Screen Shot 2021-04-27 at 11 36 58 AM" src="https://user-images.githubusercontent.com/82427400/116270280-f3870f80-a74c-11eb-8f49-a7666fb6ab6f.png">
<img width="1256" alt="Screen Shot 2021-04-27 at 11 36 53 AM" src="https://user-images.githubusercontent.com/82427400/116270282-f3870f80-a74c-11eb-8816-123bebaa0ee3.png">

**Comment by joenicolette** [comment]
@1stevengrant

**Comment by 1stevengrant** [comment]
resolved by in progress deploy
