### ISSUE TITLE
DESKTOP - No clear path back to home page after clicking Terms/Privacy

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#71]
Can we make the logo on top of the screen clickable? That was my natural inclination.

<img width="773" alt="Screen Shot 2021-04-27 at 11 38 41 AM" src="https://user-images.githubusercontent.com/82427400/116270665-4bbe1180-a74d-11eb-9339-ea70b0ebbf08.png">
<img width="747" alt="Screen Shot 2021-04-27 at 11 39 22 AM" src="https://user-images.githubusercontent.com/82427400/116270675-4d87d500-a74d-11eb-803a-e44db8332739.png">

@1stevengrant

**Comment by 1stevengrant** [comment]
resolved by in progress deploy
