### ISSUE TITLE
DESKTOP: "Donate" button text in main nav isn't centered 

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#72]
<img width="149" alt="Screen Shot 2021-04-27 at 11 39 02 AM" src="https://user-images.githubusercontent.com/82427400/116270873-7c9e4680-a74d-11eb-86b4-dd33cb01a2d4.png">

**Comment by joenicolette** [comment]
@1stevengrant

**Comment by 1stevengrant** [comment]
actually it was missing the icon as well - resolved by in progress deploy
