### ISSUE TITLE
BAM: Inactive player controls?

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#73]
Hmm...these buttons aren't clickable. Any thoughts?
<img width="1679" alt="Screen Shot 2021-04-27 at 11 59 54 AM" src="https://user-images.githubusercontent.com/82427400/116273935-30a0d100-a750-11eb-9697-4772f1ed3e1f.png">

**Comment by joenicolette** [comment]
@1stevengrant

**Comment by 1stevengrant** [comment]
@joenicolette introduced these for Android, have changed to now hide until the video plays so as not to be visible. Release in progress.
