### ISSUE TITLE
iOS: Chevron sizing under "Forever free" section

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#74]
Seem to be a bit squeezed/out of shape
![IMG_F3E02C741F5A-1](https://user-images.githubusercontent.com/82427400/116274718-e9671000-a750-11eb-8e11-dbea3dc2de18.jpeg)

@1stevengrant

**Comment by 1stevengrant** [comment]
@joenicolette do you mean the background? It was exported straight from Figma.

**Comment by joenicolette** [comment]
@1stevengrant understood
