### ISSUE TITLE
STRIPE: Can we adjust "Subscribe" to read "Donate" or something similar?

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#75]
<img width="457" alt="Screen Shot 2021-04-27 at 12 08 12 PM" src="https://user-images.githubusercontent.com/82427400/116275099-48c52000-a751-11eb-8d76-a5b069301686.png">

**Comment by 1stevengrant** [comment]
@joenicolette I don't believe so, I'll see if I can see anything on the Stripe side of things but as far as I've ever known, it's only been brand and basic text

**Comment by 1stevengrant** [comment]
@joenicolette sadly not - we're doing it for single donations but it's not possible in subscription mode :( 

From Stripe:

```
submit_type can only be specified on Checkout Sessions in payment mode, but not Checkout Sessions in subscription or setup mode.
```
