### ISSUE TITLE
Font colors on buttons

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#78]
![Screen Shot 2021-05-12 at 12 03 10 PM](https://user-images.githubusercontent.com/68758055/118007323-0afff400-b31a-11eb-89bb-3eee55977c3e.png)
![Screen Shot 2021-05-12 at 12 03 31 PM](https://user-images.githubusercontent.com/68758055/118007361-13582f00-b31a-11eb-812c-cbddba30d934.png)

Can we change the font color to white for buttons that exist on a white background? I've made the appropriate change on Figma. Also the Watch Now button to match the white text above it.

Thanks!

**Comment by 1stevengrant** [comment]
resolved
