### ISSUE TITLE
Desktop/Firefox - "Manage Your Existing Monthly Donation" button doesn't do anything

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#82]
<img width="592" alt="Screen Shot 2021-05-13 at 8 32 54 PM" src="https://user-images.githubusercontent.com/82427400/118203630-72a56480-b42a-11eb-946d-95b7b565327d.png">

@1stevengrant

**Comment by 1stevengrant** [comment]
@joenicolette can you download Firefox on your machine and check. Both my local environment and staging seem to be fine on my Firefox instance

**Comment by joenicolette** [comment]
@1stevengrant this was with Firefox downloaded on my desktop, but it's now resolved!
