### ISSUE TITLE
Desktop/Firefox - Even with fields populated, giving is disabled

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#83]
<img width="572" alt="Screen Shot 2021-05-13 at 8 35 55 PM" src="https://user-images.githubusercontent.com/82427400/118203829-e8a9cb80-b42a-11eb-9185-27e71fd17172.png">

@1stevengrant

**Comment by 1stevengrant** [comment]
@joenicolette can you download Firefox on your machine and check. Both my local environment and staging seem to be fine on my Firefox instance.

**Comment by joenicolette** [comment]
@1stevengrant this bug was found while using Firefox on my desktop, but it's fixed now!
