### ISSUE TITLE
Desktop/All Browsers - Clicking "Ask the Expert" in main nav brings you to the new hero image instead of the form

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#84]
<img width="1680" alt="Screen Shot 2021-05-13 at 8 38 55 PM" src="https://user-images.githubusercontent.com/82427400/118204089-72f22f80-b42b-11eb-96c8-9a64acae547b.png">

@1stevengrant

**Comment by 1stevengrant** [comment]
this image was part of the component. Have moved it out now and is pending release.
