### ISSUE TITLE
Desktop/Microsoft Edge - Explore parallaxing is disabled.

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#86]
<img width="1680" alt="Screen Shot 2021-05-13 at 8 50 54 PM" src="https://user-images.githubusercontent.com/82427400/118204785-037d3f80-b42d-11eb-9e64-b0e591fbb1dd.png">
@1stevengrant

**Comment by 1stevengrant** [comment]
this is a false positive with the test tools. Tested with edge on my Mac and seems to be fine.
