### ISSUE TITLE
Desktop/Windows 10/Firefox - Clicking "Ask the Expert" brought me to the "Partner with Us" section

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#87]
<img width="1656" alt="Screen Shot 2021-05-13 at 8 59 53 PM" src="https://user-images.githubusercontent.com/82427400/118205486-70450980-b42e-11eb-9db3-dc477cd2a375.png">
@1stevengrant

**Comment by 1stevengrant** [comment]
will be resolved pending deployment
