### ISSUE TITLE
Desktop/Microsoft Edge + Internet Explorer - Nearly all text fields/buttons need to be realigned/adjusted

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#88]
<img width="897" alt="Screen Shot 2021-05-13 at 8 53 27 PM" src="https://user-images.githubusercontent.com/82427400/118205096-a3d36400-b42d-11eb-9703-97588938c7e5.png">
<img width="325" alt="Screen Shot 2021-05-13 at 8 52 25 PM" src="https://user-images.githubusercontent.com/82427400/118205097-a46bfa80-b42d-11eb-8428-7cda2b88c644.png">
<img width="156" alt="Screen Shot 2021-05-13 at 8 49 39 PM" src="https://user-images.githubusercontent.com/82427400/118205107-a8981800-b42d-11eb-8006-0cf887ccda49.png">

@1stevengrant

**Comment by 1stevengrant** [comment]
@joenicolette was this browserstack edge or on your Mac? My edge seems to be fine.

**Comment by joenicolette** [comment]
@1stevengrant this was browserstack edge.
