### ISSUE TITLE
Mobile/Samsung S21 - Explore parallaxing isn't working.

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#89]
<img width="470" alt="Screen Shot 2021-05-13 at 9 04 43 PM" src="https://user-images.githubusercontent.com/82427400/118205900-77204c00-b42f-11eb-8fd0-4280dfa4a6a2.png">

@astevengrant

**Comment by 1stevengrant** [comment]
should be good now on this. I tested with a sub $50 Android handset Sarah had from her last job and seems to be sweet on my test https://d.pr/v/faLOqN
