### ISSUE TITLE
MacBook Pro, font too large on buttons

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#9]
<img width="1403" alt="Screen Shot 2021-04-11 at 7 12 43 PM" src="https://user-images.githubusercontent.com/68758055/114324770-e71e7800-9af9-11eb-8263-a7ba3a2026d3.png">

**Comment by 1stevengrant** [comment]
@gitethanwoo Figma is showing the text size should be 36px - is this wrong ?

**Comment by gitethanwoo** [comment]
You're right - the font size is 36 in Figma. The desktop experience on Figma only uses one video panel though, so when there's three, I think it's squishing the buttons down and thus making the font look too big

**Comment by 1stevengrant** [comment]
resolved
