### ISSUE TITLE
Mobile/Samsung S21 - Clicking "Ask the Expert" in the main nav brings me between components

### ISSUE THREAD

**Issue by joenicolette** [loveology/issues#90]
<img width="370" alt="Screen Shot 2021-05-13 at 9 05 04 PM" src="https://user-images.githubusercontent.com/82427400/118205954-9323ed80-b42f-11eb-8e9e-55afdcce41ed.png">
@1stevengrant

**Comment by 1stevengrant** [comment]
image being part of the component is the issue. Resolved pending deployment.
