### ISSUE TITLE
Button problems.. with a suggestion!

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#96]
![Screen Shot 2021-05-20 at 5 26 09 PM](https://user-images.githubusercontent.com/68758055/119051417-22318800-b991-11eb-84d3-dae27a7d86d4.png)

I've looked at the button across a few different breakpoints - Seems likes its difficult to find the exact padding that fixes it. On small screens, the text is almost perfect, but the button is a few pixels too low. On bigger screens, the play button is perfect, but the text is about 5 pixels too high. My suggestion is to try a sans serif analog like Arial for this particular case. It looks really close. Could be a relatively simple solution until the issues with the font are fully remedied.

**Comment by 1stevengrant** [comment]
good news, it was down to the font files. Updated with the new ones and the consistency is there now. Also impacting here was the icon size itself. What I've done for the icons is set a standard canvas size of 256px x 256px in Illustrator and then bring the icon from Figma in to match that size where appropriate and center within the canvas. Keeps everything nice and even and then we can scale the icon with CSS.
