### ISSUE TITLE
Is it possible to increase left padding to 3rem on "submit" buttons?

### ISSUE THREAD

**Issue by gitethanwoo** [loveology/issues#98]
![Screen Shot 2021-05-24 at 1 07 07 PM](https://user-images.githubusercontent.com/68758055/119383148-febc5500-bc90-11eb-8140-327fad25e1bb.png)

Also: On this particular button with 2xl text, can we increase the Chevron size from w-4,h-4 to w-6, w6?

Hopefully it looks like this after:
![Screen Shot 2021-05-24 at 1 06 55 PM](https://user-images.githubusercontent.com/68758055/119383177-03810900-bc91-11eb-9fd9-0a386bef99c6.png)

**Comment by gitethanwoo** [comment]
WATCH NOW button is fine. The "menu-link" button could decrease the right padding from 1.5rem to 1.25 rem

**Comment by 1stevengrant** [comment]
@gitethanwoo do we want these changes to be reflected on all screen sizes or just desktop?

Remember we can define the responsive variants by doing `md:w-6 md:h-6`  

The `watch now` button I had to make an exception for because it changes the text to uppercase - also the mobile and desktop versions trigger different events.

**Comment by 1stevengrant** [comment]
The variants we can cater for:

md (768px-1023px wide)
lg (1024px-1279px wide)
xl (1280px-1535px wide)
2xl (1536px-2500px wide)
bam (2500px+ wide)

**Comment by gitethanwoo** [comment]
All screen sizes.

**Comment by 1stevengrant** [comment]
got it. In that case, should the text size not also become consistent across all screen sizes too?

I'm thinking specifically about the `donate now` and `ask a question` buttons. If you increase the icon without giving the text the same treatment (bumping to `text-2xl`)

**Comment by gitethanwoo** [comment]
ooh sorry, let me be more explicit. I misunderstood. I think all the "submit" buttons need 3rem left padding across all screens. But you're totally right and I missed it: the "keep me updated" button needs md:w-6 md:h-6. I didn't realize the font changed with screen size. The "donate now" and "ask a question" buttons can follow suite, too! md:text-2xl pl-12 and for the SVG,  md:w-6 md:h-6

**Comment by 1stevengrant** [comment]
all buttons with the exception of the hero player follow the same pattern
